# Generated by Django 5.2 on 2025-04-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testsets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.FloatField()),
                ('passed', models.BooleanField()),
                ('duration_minutes', models.IntegerField()),
                ('testset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsets.testset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsets.question')),
                ('selected_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testsets.option')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempts.testattempt')),
            ],
        ),
    ]
